#!/bin/bash

# get whereami from: https://github.com/robmathers/WhereAmI
WHEREAMI="$HOME/whereami"

# register for an OpenCage Geocoder API key here:
# https://opencagedata.com
#
# probably best to use an environment variable, not hard code it here
#
OPENCAGE_API_KEY="YOUR-API-KEY"

# get the location, 5th line of output
LOCATION=`$WHEREAMI -k $OPENCAGE_API_KEY | awk '0 == NR % 5'`

# print it
printf "\ncommited from: $LOCATION\n" >> $1
